Capstone-project
rbd3/RBD-High-School pull request #1
Opened 2023-05-24 08:32 UTC by rbd3

### Change made:
👉 Add HTML for content
👉 Add CSS for styling
👉 Add js code for dynamic Teachers
👉 Add mobile version
👉 Add desktop version

2023-05-24 13:24 UTC, NahnahAJ requested changes
## Project Status: CHANGES REQUIRED :recycle: 
Hi @rbd3 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Highlights
- Very nice design ✔️
- Good use of GitHub flow ✔️
- No linter errors ✔️
- Professional README ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-24 13:24 UTC, nahnahdev commented on index.html
> +          </ul>
- [ ] Great job so far @rbd3 Your project looks great 💯 There are just a few changes you need to make and you'll be on your way to the next milestone 👍 
- [ ] I noticed that in your `nav`, these list items aren't well centered as seen in the original design and they are also missing the orange hover effect as seen in the behance design so kindly implement these as well 💯 

| Your Design | The Behance Design |
|--------|--------|
|<img width="620" alt="Screen Shot 2023-05-24 at 12 10 01 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/52a41d6c-781e-4097-868d-064a02bcf1b7"> | <img width="359" alt="Screen Shot 2023-05-24 at 12 14 07 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/fe319a5c-a066-4d7c-b274-1b9235aca099"> |

2023-05-24 13:24 UTC, nahnahdev commented on index.html
> +            <p class="description">RBD School is a premier high school in Madagascar specializing in computer science,
- [ ] Your headline section looks great. There is just a small change I will suggest. I will suggest that you ensure that the headline section has the text` RABEDESANA HIGH SCHOOL FOR TECHNOLOGY 2023 ` styled as seen in the Behance Design 👍 
- [ ] From the Behance design, you can see that it spans across 3 lines hence giving it a shorter width compared to what you currently have in your Design 💯
- Your Design
<img width="892" alt="Screen Shot 2023-05-24 at 12 20 06 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/39bc3881-a451-46df-9679-b005125c7af7">

- The Behance Design
<img width="554" alt="Screen Shot 2023-05-24 at 12 20 26 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/f26afaac-5146-40ca-ac9d-3bf51f708dcb">

2023-05-24 13:24 UTC, nahnahdev commented on index.html
> +        </section>
- [ ] When the `headline section` ends, there is a white spacing between that section and the `main program ` section which wasn't present in the Behance design so kindly remove this spacing from your design so your design follows the given design guidelines 💯 
- Your Design
<img width="1266" alt="Screen Shot 2023-05-24 at 12 24 33 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/67f3e68e-e67a-44d0-ac42-8d370548b9a6">

- The Behance Design
<img width="838" alt="Screen Shot 2023-05-24 at 12 27 37 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/f08075b6-7faa-42f2-8ca7-be863fe5f769">

2023-05-24 13:24 UTC, nahnahdev commented on index.html
> +              <h3 class="program-title">Education</h3>
- [ ] Please style these texts as seen in the Behance design. They should be bolder as seen in the original design so your design looks similar to the original design 👍 
- [ ] Please do these for all the other cards as well 👍 

| Your Design | The Behance Design |
|--------|--------|
|<img width="219" alt="Screen Shot 2023-05-24 at 12 34 59 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/a95f8e66-bdc9-4e73-bc19-89aa1408373c">| <img width="122" alt="Screen Shot 2023-05-24 at 12 30 29 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/e6a30f74-648d-44d6-8c0d-90ffc9ea8e9a"> |

2023-05-24 13:24 UTC, nahnahdev commented on script.js
> +  },
- [ ] For the Featured Teachers section, please ensure that the size of the images are similar to that of the behance design. 👍
- [ ] There is also a checkered background image on the top left corner of the images which you are currently missing in yours so kindly include this in your design as well 👍 
- [ ]  I also noticed that the names of the teachers aren't styled as seen in the original design, and the profession of the speakers in the orange color are also missing the Italic effect applied to them as seen in the original design so kindly include this 😉
- [ ] Please do this for both desktop and Mobile 👍
- Your Design
<img width="455" alt="Screen Shot 2023-05-24 at 12 46 36 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/b0144bbb-ede1-481f-9aba-29db5306d98b">

- The Behance Design
<img width="343" alt="Screen Shot 2023-05-24 at 12 47 08 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/79094bfe-490d-434b-a950-c314a6551ab3">

2023-05-24 13:24 UTC, nahnahdev commented on about.html
> +         </section>
- [ ] In the Behance design, the About Page needed to have 3 sections. But currently you only have two.
- [ ]  I noticed that you're currently missing the middle section which should be a centered column that includes a section header, a divider, a paragraph of text, and an image or large logo. I have included an image of the Behnace Design Below 😉
- The Behance Design
<img width="745" alt="Screen Shot 2023-05-24 at 12 58 34 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/3552757a-4e9c-4e06-94c5-fa2581acacb6">

2023-05-24 13:24 UTC, NahnahAJ commented on about.html
> +          </section>
- [ ] In the third section, I noticed that you're missing the short line of text that come underneath the orange divider. So kindly include this in your design and ensure that the spacing around your design and between the elements is similar to that of the Behance Design 👍 
- Your Design
<img width="876" alt="Screen Shot 2023-05-24 at 1 03 50 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/aa339cff-1e14-4b83-9f7a-661a491aefc4">
- The Behance Design
<img width="622" alt="Screen Shot 2023-05-24 at 1 04 31 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/f3dd670f-097d-48d9-9cbb-63e1ebd30f10">

2023-05-24 13:24 UTC, NahnahAJ commented on about.html
> +
- [ ] Your footer currently doesn't have the black background color spanning across the entire width of the page as seen in the original design so kindly fix this as well 👍 
- [ ] I noticed a similar problem in your mobile view. So kindly fix that as well 👍 

- Your Design
<img width="1280" alt="Screen Shot 2023-05-24 at 1 09 39 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/ce9bb80e-0889-4cce-ab91-68d1fe24a234">

- The Behance Design
<img width="741" alt="Screen Shot 2023-05-24 at 1 10 15 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/e876b4ab-1f42-4b3b-8ed6-9c4761270c63">

- Your Mobile Design
<img width="292" alt="Screen Shot 2023-05-24 at 1 18 14 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/9b5f01d0-0951-4564-ab37-836a98bd2966">

2023-05-24 13:24 UTC, NahnahAJ commented on index.html
> +            </div>
- [ ] When on the mobile view, the `h3` texts with the orange color are smaller as compared to the original design so kindly fix this as well 👍 

| Your Design | The Behance Design |
|--------|--------|
| <img width="275" alt="Screen Shot 2023-05-24 at 1 13 49 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/c5de0d03-a3af-4d27-9f8d-4f3d27b5c42f"> | <img width="383" alt="Screen Shot 2023-05-24 at 1 16 12 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/64f2074f-c887-4ebf-aa29-c6460246170e">
 |

2023-05-24 13:26 UTC, NahnahAJ commented
- [ ] Hello @rbd3 I mistakenly approved your project on the Dashboard instead of requesting changes but I have already reported it so you can go on with your changes it'll be changed back very soon 👍

2023-05-24 14:20 UTC, enniopo commented
Hi @rbd3 your dashboard has been updated and you can request a new code review as soon as you are ready. Thank you

2023-05-25 09:41 UTC, AlphaNtihinduka requested changes
## Hi @rbd3 🙋‍♂️
Good job working on your high school project. You have done the design to the best expectation and incredibly well. 👏  

You still need to implement few on the project but you are almost there!!! 🚶. 

TO HIGHLIGHT:
- Dynamic display of speakers ✔️ 
- Mobile menu works as expected ✔️ 
- Your PR is professional ✅
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

## Optional suggestions
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-05-25 09:41 UTC, AlphaNtihinduka commented on index.html
> +              <h3 class="program-title">Education</h3>
-  If you notice, its only the `program-title` that should be bold as suggested by the previous review. Kindly reduce the font-weight on the `program-detail` so that the texts are visible and also make the title bold to match the original design ☺️.

Your design 😎 
![image](https://github.com/rbd3/RBD-High-School/assets/99394374/f94cd145-7e10-4b27-93ba-a633a8b1212c)

Original design 😎 
![image](https://github.com/rbd3/RBD-High-School/assets/99394374/36933fe1-f809-4941-88f2-3228381a5bb1)

2023-05-25 13:11 UTC, NahnahAJ approved these changes
## Project Status: APPROVED :green_circle: 
Hi @rbd3 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
- All requested changes implemented ✔️ 
- No linter errors ✔️ 
- Nice Design ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-25 13:11 UTC, NahnahAJ commented on index.html
> +          </ul>
- [ OPTIONAL ] Great job @rbd3 I noticed you added a logo to your Project. However the problem is that now some of the `nav` items in your mobile menu are overlapping over each other. I will suggest you fix this to improve your project as well as user interaction 😉  
- Your current Design
<img width="316" alt="Screen Shot 2023-05-25 at 12 59 51 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/251cb434-ea6b-4eab-baac-2f1f4ce6bbc1">

2023-05-25 13:11 UTC, NahnahAJ commented on index.html
> +        <div id="teachers-container" class="teachers-container flex column">
- [ OPTIONAL ] I noticed that the images appear squished together. This display issue is not in line with the intended design and can negatively impact the overall user experience.

- It is important to ensure that images are displayed properly and maintain their intended aspect ratio, even in mobile view. Squished images can lead to distorted visuals and make it difficult for users to fully appreciate the content you are presenting. 
- So I will suggest you fix this as well so you can ensure that the mobile view aligns with the intended design and provides a more visually appealing and user-friendly experience for your visitors. 😉 
- Your Design
<img width="314" alt="Screen Shot 2023-05-25 at 1 04 48 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/68694871-3fdf-445a-ad94-2ceac0e384a2">

2023-05-25 13:11 UTC, NahnahAJ commented on about.html
> +            </div>
- [ OPTIONAL ] These texts need to be properly centered on the page as seen in the original design so I will suggest you incorporate this as well 👍  
- That way you can ensure that your design aligns with the intended design and provides a more visually appealing and user-friendly experience for your visitors. 💯 
- Your Design
<img width="1167" alt="Screen Shot 2023-05-25 at 1 08 44 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/58662cf3-1c0d-4192-b3bc-ab54b1563b63">
- The Behance Design
<img width="674" alt="Screen Shot 2023-05-25 at 1 09 30 PM" src="https://github.com/rbd3/RBD-High-School/assets/102699958/7e5b3242-6586-48de-89ad-b61dd21b7d24">

2023-05-25 14:07 UTC, merged